-- lua/keymaps.lua
local map = vim.keymap.set

map('n', '<leader>q', ':q!<CR>', { desc = 'Quit without saving' })
map('n', '<leader>u', ':lua require("fff.download").download_or_build_binary()<CR>', { desc = 'Update the FFF binary' })
map('n', '<leader>f', function()
  require('fff').find_files()
end, { desc = 'Find Files' })
map('n', '<leader>e', function()
  Snacks.explorer()
end, { desc = 'File Explorer' })
map('n', '<leader>b', function()
  Snacks.picker.buffers()
end, { desc = 'Find Buffers' })
map('n', '<leader>/', function()
  require('fff').live_grep()
end, { desc = 'Grep' })
map('n', '<leader>lg', function()
  Snacks.lazygit.open()
end, { desc = 'Open Lazygit' })
map('n', '<Tab>', ':bprev<CR>', { desc = 'Previous Buffer' })
map('n', '<S-Tab>', ':bnext<CR>', { desc = 'Next Buffer' })
map('n', '<leader>c', function()
  require('fff').find_files_in_dir(vim.fn.expand '~/nixdots')
end, { desc = 'Open NixOS Configs' })
