vim.pack.add({
	"https://github.com/dmtrKovalenko/fff.nvim",
	"https://github.com/f4z3r/gruvbox-material.nvim",
	"https://github.com/folke/snacks.nvim",
	"https://github.com/folke/which-key.nvim",
	"https://github.com/nvim-mini/mini-ai",
	"https://github.com/nvim-mini/mini-icons",
	"https://github.com/nvim-mini/mini-notify",
	"https://github.com/nvim-mini/mini-pairs",
	"https://github.com/nvim-mini/mini-statusline",
	"https://github.com/nvim-mini/mini-surround",
	"https://github.com/stevearc/conform.nvim",
	-- "https://github.com/neovim/nvim-lspconfig",
	{ src = "https://github.com/Saghen/blink.cmp", version = vim.version.range("*") },
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", branch = "main" },
})
